### ISSUE TITLE
Foundry 12 Compatibility: Cannot create QE by selecting tokens and pressing the Token Controls>Create a QE button

### ISSUE THREAD

**Issue by spetzel2020** [spetzel2020/quick-encounters#142]
1. A Journal Entry is created, but without anything in it

**Comment by spetzel2020** [comment]
Fixed in 1.2.3g (not released)

**Comment by spetzel2020** [comment]
Released in v1.2.3

**Comment by kylania** [comment]
I'm still getting this error after a fresh install of QE 1.2.3 on standalone Version 12 Stable 327 Foundry VTT.  Each time I click the QE button I just get another blank How to Use Journal Entry.  If I double click an encounter map icon I'd previously created, I just get the Journal Entry, no option to run the Encounter.

Video reproduction: https://drive.google.com/file/d/1ScCGbXsXkf8K9CmVMm0eGWecgv8Jd3C-/view?usp=drive_link

**Comment by spetzel2020** [comment]
Ok, thanks for the update. I will need more info to reproduce which I will
ask for soon.

**Comment by spetzel2020** [comment]
Thanks for the very helpful video! It looks like this may be a new problem, because you can create the QE and when you double-click the Map Icon the first time it produces the QE dialog (although you didn't show the Run QE result).

The second time you open the Journal Entry, the QE Dialog doesn't show. Can you try two things: 
1. In Configure Settings, under Quick Encounters, what is the setting of the "Show QE Dialog automatically" setting?
2. When you reopen the Journal Entry, and the QE doesn't show, what happens when you click on "Show QE" on the Journal Entry header (border).

**Comment by spetzel2020** [comment]
Also when you don't have tokens selected, then clicking the QE button will (correctly) give you the Tutorial.

If the QE Map Note is disappearing, check the setting of Journal Notes>Toggle Note Display in the left hand Control Menu

**Comment by spetzel2020** [comment]
No worries on the Show QE!

And you are quite right that the Tutorial text is not showing. I will
create a new Issue for that. Hopefully an easy fix.

**Comment by spetzel2020** [comment]
Re your: 
> And it would be useful to have an option to have the red QE map note maybe be 1/2 as large as it currently is?
Although there is no existing option, a workaround (which you may already know about) is that in Journal Notes mode (from the left-hand menu) you can double-right-click on a Map Note and shrink the Icon size (currently 80)
